### ISSUE TITLE
Install plumi.app on centos

### ISSUE THREAD

**Issue by wukaMM** [plumi/plumi.app#10]
Hi~
I am try to install plumi.app on centos system, and in the file buildout.cfg:
extends =
    base.cfg
    site.cfg
    build.cfg
    versions.cfg
I am wondering the "versions.cfg" is which one?
Thank you~

**Comment by rrezel** [comment]
Hi,

I'm also trying to set this up. Try copying https://github.com/plumi/plumi.app/blob/master/versions/known-good-versions.cfg and renaming it as versions.cfg.

It might work.

**Comment by mgogoulos** [comment]
instructions are updated on the main readme of this repository for installing plumi on centos 7
