### ISSUE TITLE
Problem when installing plumi on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [plumi/plumi.app#20]
Hi,

I am trying to install plumi on Ubuntu 14.04. The system is completely new and has no additional libraries installed.

All the process is following the https://mgogoulos.trinket.io/plumi-4-5#/.
1. I was stuck by the "python bootstrap.py"

In this step, I was stuck by the "  File "bootstrap.py", line 60, in <module>
    exec urllib2.urlopen('http://python-distribute.org/distribute_setup.py'
urllib2.HTTPError: HTTP Error 404: Not Found". 
I suppose the reason is that the URL is no longer maintained. 

I tried to find an alternative "http://web.archive.org/web/20140625122200/http://python-distribute.org/distribute_setup.py". However, it is still not successful. Here is the trace:

Traceback (most recent call last):
  File "bootstrap.py", line 75, in <module>
    ws.find(pkg_resources.Requirement.parse(requirement)).location
AttributeError: 'NoneType' object has no attribute 'location'
1. So I tried to directly use the "buildout -Nv", but I got the following problem.

Installing 'buildout.dumppickedversions', 'mr.developer'.
/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py:187: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Picked: buildout.dumppickedversions = 0.5
Picked: mr.developer = 1.34
Egg from site-packages: zc.buildout 1.7.1
While:
  Installing.
  Loading extensions.
Error: There is a version conflict.
We already have: setuptools 25.1.6
1. Then I have to try installing directly from the pip.

pip2 install plumi.app

Unfortunately, still not successful. Here is the error:

No files/directories in /tmp/pip-build-5asR0o/ZEO/pip-egg-info (from PKG-INFO)

I don't know what happened.

These problems really drive me crazy. Can you help me out of these problems?

**Comment by artb1sh** [comment]
Update bootstrap.py for new
https://github.com/buildout/buildout/blob/master/bootstrap/bootstrap.py

**Comment by mgogoulos** [comment]
buildout is now tested on Ubuntu 16.04, check instructions on the README.rst
