### ISSUE TITLE
Publish video

### ISSUE THREAD

**Issue by artb1sh** [plumi/plumi.app#21]
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module plumi.content.browser.reTranscode, line 13, in **call**
  Module collective.transcode.star.utility, line 78, in add
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 12: ordinal not in range(128)

**Comment by artb1sh** [comment]
I am click "You may like to try to re-start transcoding."

**Comment by artb1sh** [comment]
BAWWWW Help
30minutes 
Transcode Status
webm-high - 0% webm-low - 0% jpeg - 0% mp4-high - 0% mp4-low - 0%

How view log 

`INFO:collective.transcode:['iso', 'jpeg', 'mpeg2', 'mp4-high', 'mp4-low', 'webm-high', 'webm-low']
ERROR:collective.transcode:Invalid transcode request: checksum mismatch
ERROR:collective.transcode:Invalid transcode request: checksum mismatch
ERROR:collective.transcode:Invalid transcode request: checksum mismatch
ERROR:collective.transcode:Invalid transcode request: checksum mismatch
ERROR:collective.transcode:Invalid transcode request: checksum mismatch
ERROR:collective.transcode:Invalid transcode request: checksum mismatch
`

**Comment by artb1sh** [comment]
[warn] [/file[0]/padding] padding contents doesn't look normal (invalid pattern at byte 0)!
[warn] [/file[0]/uid] Unable to convert string to Unicode: 'ascii' codec can't decode byte 0xa3 in position 6: ordinal not in range(128)
[warn] [/file[0]/padding] padding contents doesn't look normal (invalid pattern at byte 0)!
[warn] [/file[0]/uid] Unable to convert string to Unicode: 'ascii' codec can't decode byte 0xa3 in position 6: ordinal not in range(128)

**Comment by mgogoulos** [comment]
```
ERROR:collective.transcode:Invalid transcode request: checksum mismatch 
```

is usually produced if the secret id is different in site.cfg than on the transcode settings (on plumi settings). 

I'm assuming the other issue is no more an issue
