### ISSUE TITLE
Error installing vpx-build (404) while running buildout 

### ISSUE THREAD

**Issue by ve3lst** [plumi/plumi.app#23]
Hi,

I'm trying to install plumi on Ubunutu 16.04 but now I'm stuck at buildout step, I get an error when installing vpx-build:

> server@server-AOD257:/opt/plumi/plumi.app/ffmpeg$ ./bin/buildout
Unused options for buildout: 'develop-eggs'.
Updating yasm-build.
Updating pcre-source.
Updating x264-build.
Updating ogg-build.
Updating vorbis-build.
Updating theora-build.
Updating faac-build.
Updating faad-build.
Installing vpx-build.
vpx-build: [ENV] PATH = /opt/plumi/plumi.app/ffmpeg/parts/yasm-build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Downloading http://webm.googlecode.com/files/libvpx-v1.1.0.tar.bz2
While:
  Installing vpx-build.
Error: Error downloading extends for URL http://webm.googlecode.com/files/libvpx-v1.1.0.tar.bz2: HTTP Error 404: Not Found

I've tried updating buildout using this one: [https://github.com/buildout/buildout/blob/master/bootstrap/bootstrap.py](url) but no luck.

What can I do here?

Thanks!

**Comment by artb1sh** [comment]
libvpx = http://pkgs.fedoraproject.org/repo/pkgs/libvpx/libvpx-v1.1.0.tar.bz2/7ae163ac3196c79ec2f0904280078a45/libvpx-v1.1.0.tar.bz2

**Comment by artb1sh** [comment]
Also Pluni It does not work, throw, no transcode

**Comment by mgogoulos** [comment]
the buildout is now updated, please check the installation docs on README.rst
