### ISSUE TITLE
UWSGI error

### ISSUE THREAD

**Issue by artb1sh** [plumi/plumi.app#25]
mapping worker 2 to CPUs: 1
Respawned uWSGI worker 1 (new pid: 8045)
mapping worker 1 to CPUs: 0
Loading paste environment: config:/opt/plumi.app/production.ini
ImportError: No module named paste.script.util.logging_config
ImportError: No module named paste.deploy
Loading paste environment: config:/opt/plumi.app/production.ini
ImportError: No module named paste.script.util.logging_config
ImportError: No module named paste.deploy

**Comment by mgogoulos** [comment]
Please do a git pull and make sure buildout.cfg contains this section

```
[uwsgi-init]
# Set the uwsgi init file containing the pythonpath
# unweb.recipe.uwsgi produces an xml file and uwsgi on Debian jessie
# will segfault once started
recipe = plone.recipe.command
command = ${buildout:directory}/bin/python ${buildout:directory}/scripts/uwsgi_init_pythonpath
update-command = ${uwsgi-init:command}
stop-on-error = false
```

at the end

Then re-reun buildout
```
./bin/buildout -vN
```

This should produce 2 files on parts/uwsgi/

```
root@jesika:/home/plumi.app# ls parts/uwsgi/
uwsgi.txt  uwsgi.xml
```

Now re-start uwsgi
```
./bin/supervisorctl restart uwsgi
```

**Comment by artb1sh** [comment]
Thanx!

**Comment by artb1sh** [comment]
![screenshot_20161130_195515](https://cloud.githubusercontent.com/assets/4118703/20762315/fe23f9f4-b736-11e6-8a78-e0759c9616a2.png)
