### ISSUE TITLE
Error downloading extends for URL while installing in Debian

### ISSUE THREAD

**Issue by jarleigel** [plumi/plumi.app#31]
Hi!
Has anyone else got this error while running  ./bin/python bootstrap.py && ./bin/buildout -v:
Error: Error downloading extends for URL http://good-py.appspot.com/release/plone.app.theming/1.0: HTTP Error 404: Not Found

I try to follow this guide: https://mgogoulos.trinket.io/plumi-4-5#/installation/installation on a totally clean Debian 8.8 installation.

Regards,
Jarle

**Comment by mgogoulos** [comment]
Seems that http://good-py.appspot.com/ is down, so better try again in a few hours if it is up!

**Comment by jarleigel** [comment]
Anybody know if there is an alternative to good-py.appspot.com?
Jarle

**Comment by krish0005** [comment]
Hi,

I'm still trying to find an alternative repository but without luck.

I got the following error and the mirror does not come back online after nearly a month now:

```
./bin/python bootstrap.py && ./bin/buildout -v
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmp_3DTvA
Now working in /tmp/tmp_3DTvA/setuptools-33.1.1
Building a Setuptools egg in /tmp/tmplInC32
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/tmplInC32/setuptools-33.1.1-py2.7.egg
no previously-included directories found matching 'doc'
no previously-included directories found matching 'old-tutorial'

While:
  Initializing.
Error: Error downloading extends for URL http://good-py.appspot.com/release/plone.app.theming/1.0: HTTP Error 404: Not Found
```

We definitively need a new mirror for this or the compilation of the site is not possible and new developments are blocked.

@mgogoulos  which code was hosted in that repo ? what can we look for to found another repository ?

I read somewhere that we need plone.app.theming/1.1 for Plone 4.5,
but would really like to have exactly the same code used originally.

If we find the files, i may also try to host the repository via githhub or expose it on one of our public servers.

**Comment by krish0005** [comment]
It is still possible to download the files from here:

[https://pypi.python.org/pypi/plone.app.themi1.0ng/1.0](url)

[https://pypi.python.org/packages/36/e4/95b2843d174c5ed0ea1fc98fd094f3eb7567b324a19bf1df0ee62a283033/plone.app.theming-1.0.zip](url)

But the Python site still references the now dead good-py service in the installation guidelines:

> To add plone.app.theming to our setup, we need some slightly different versions of a couple of the packages, so we extend the base config with a version list from the good-py service, so change this part of the configuration so it looks like this:

```
extends =
    versions.cfg
    http://good-py.appspot.com/release/plone.app.theming/1.0b1
versions = versions
```

Shall we try to host the content of : 

[https://pypi.python.org/packages/36/e4/95b2843d174c5ed0ea1fc98fd094f3eb7567b324a19bf1df0ee62a283033/plone.app.theming-1.0.zip](url)

On some public repository on SVN, GIT or anything else ?

**Comment by mgogoulos** [comment]
This is sad! I'll try during the weekend to find possible solutions and will write here

**Comment by krish0005** [comment]
Thanks Markos ! This is highly appreciated !

If it can be useful to you i already created this GitHub mirror on my account:

https://github.com/krish0005/plone.app.theming.1.0

I could not use it from the buildout since the GitHub redirects breaks the download of the files (/blob/filename...) but i was already trying to host it on an Apache2 like a normal HTTP folder..

Let me know if you need it, i might continue working on that if you really need me to host it.

Thanks!

**Comment by mgogoulos** [comment]
I've tried removing this broken url and then run buildout. It finishes without problem, portal loads and I don't see anything strange. 

So either perform a 'git pull' to get the latest buildout.cfg file, or edit this file and remove the line with good-py.appspot

Cheers,
Markos
