### ISSUE TITLE
https://github.com/plumi/plumi.app/blob/master/bootstrap.py

### ISSUE THREAD

**Issue by gunawanw9** [plumi/plumi.app#5]
line 60 http://python-distribute.org/distribute_setup.py <--- this url does not exist, long gone...

**Comment by cwadge** [comment]
Somebody was kind enough to mirror it here on GitHub: https://gist.githubusercontent.com/anonymous/947191a4635cd7b7f79a/raw/36054b7f8d7b0c4c172628fd9bd16f46e53bb34b/distribute_setup.py

**Comment by angelrr7702** [comment]
this problem still make it fail to install ..... when it try to load file http://python-distribute.org/distribute_setup.py     show HTTP Error 404: Not Found

please replace that url in the code with one that work .....

**Comment by dbinoj** [comment]
I have created a pull request https://github.com/plumi/plumi.app/pull/18 with the above Github Gist. Can anyone verify the accuracy of the gist?

**Comment by mgogoulos** [comment]
closing, this works now
